name: flutter_web_assembly_sandbox

packages:
  - ./

sdkPath: '.fvm/flutter_sdk'

scripts:
  hosting:wasm:
    #  masterチャンネルでrecordsがあるとビルドエラーになるため`--enable-experiment=records`指定
    run: |
      flutter build web --wasm --enable-experiment=records
      cd ./firebase
      firebase deploy --only hosting:wasm

  hosting:js:
    run: |
      flutter build web --web-renderer canvaskit --enable-experiment=records
      cd ./firebase
      firebase deploy --only hosting:js

  hosting:html:
    run: |
      flutter build web --web-renderer html
      cd ./firebase
      firebase deploy --only hosting:html
